Back/Controllers/MainController.cs
using Back.App_Start;
using System.Web.Mvc;

namespace Back.Controllers
{
    [AuthorizationFilter]
    public class MainController : Controller
    {
        // GET: Main
        public ActionResult Index()
        {
            return View();
        }
    }
}

Back/Controllers/MenuController.cs
using Back.App_Start;
using Back.Helpers;
using Back.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Back.Controllers
{
    [AuthorizationFilter]
    public class MenuController : Controller
    {
        //GET: Menu
        public ActionResult MenuItems()
        {
            try
            {
                List<vBack_Menu> _list = new List<vBack_Menu>();
                HttpResponseMessage _response = WebApiHelper.p_AEPSAD_Request(WebApiHelper.ENDPOINT_MENU_GETALL);

                if (_response.IsSuccessStatusCode)
                {
                    var _json = _response.Content.ReadAsStringAsync().Result;

                    _list = JsonConvert.DeserializeObject<List<vBack_Menu>>(_json);
                }
                else
                {
                    ErrorHelper.p_AEPSAD_Log(_response.StatusCode.ToString());
                }

                if (_list == null)
                    return View(new List<vBack_Menu>());

                _list = _list.OrderBy(x => x.ModuloId).OrderBy(x => x.MenuGrupoId).ToList();

                return View(_list);
            }

            catch (Exception ex)
            {
                ErrorHelper.p_AEPSAD_Log(ex);

                return RedirectToAction(ConfigHelper.URL_ERROR + "?" + ErrorHelper.ERROR_VARIABLE + "=" + ErrorHelper.ERROR_EXEC_KEY);
            }
        }

        public ActionResult CrearMenuItems()
        {
            Menu _m = new Menu
            {
                GruposMenu = DropDownListHelper.p_AEPSAD_MenuGrupos()
            };


            return View(_m);
        }

        [HttpPost]
        public ActionResult CrearMenuItems(Menu model, HttpPostedFileBase IconoFile)
        {  
            try
            {
                model.GruposMenu = DropDownListHelper.p_AEPSAD_MenuGrupos(model.MenuGrupoId);

                String _error = String.Empty;
                String _icono = String.Empty;

                bool _isFileUploaded = UploadImageHelper.p_AEPSAD_UploadImage(IconoFile, "IconoMenu_" + model.Id, ref _icono, ref _error);

                if (!_isFileUploaded)
                {
                    ModelState.AddModelError("IconoFile", _error);
                }

                if (!ModelState.IsValid)
                {
                    return View(model);
                }


                HttpClient _client = WebApiHelper.p_APESAD_HttpClient(SessionHelper.p_AEPSAD_get_usuario().Token);

                MenuModel _m = new MenuModel
                {
                    Id = model.Id,
                    MenuGrupoId = model.MenuGrupoId,
                    Texto = model.Texto,
                    Enlace = model.Enlace,
                    Icono = _icono,
                    NuevaVentana = (model.NuevaVentana ? Convert.ToByte(1) : Convert.ToByte(0)),
                    Orden = model.Orden
                };

                var _json = JsonConvert.SerializeObject(_m);
                var _content = new StringContent(_json.ToString(), Encoding.UTF8, "application/json");

                HttpResponseMessage _response = _client.PostAsync(WebApiHelper.ENDPOINT_MENU_CREATE, _content).Result;

                if (_response.IsSuccessStatusCode)
                {
                    ViewBag.JavaScriptFunction = string.Format("p_AEPSAD_save_ok('Los datos han sido creados');");
                }
                else
                {
                    ErrorHelper.p_AEPSAD_Log(_response.ReasonPhrase);
                    ViewBag.JavaScriptFunction = string.Format("p_AEPSAD_error('" + _response.ReasonPhrase + "');");
                }

                return View(model);
            }
            catch (Exception ex)
            {
                ErrorHelper.p_AEPSAD_Log(ex);
                ViewBag.JavaScriptFunction = string.Format("p_AEPSAD_error('" + ex.Message + "');");
                return View(model);
            }
        }
        
        [HttpGet]
        public ActionResult EditarMenuItems(String id)
        {
            Menu _m = new Menu();

            try
            {
                List<Menu> _list = new List<Menu>();
                HttpResponseMessage _response = WebApiHelper.p_AEPSAD_Request(WebApiHelper.ENDPOINT_MENU_GETONE + id);

                if (_response.IsSuccessStatusCode)
                {
                    var _json = _response.Content.ReadAsStringAsync().Result;

                    _list = JsonConvert.DeserializeObject<List<Menu>>(_json);

                    if (_list.Count > 0)
                    {
                        _m = _list[0];
                        _m.GruposMenu = DropDownListHelper.p_AEPSAD_MenuGrupos(_m.MenuGrupoId);
                    }
                }
                else
                {
                    ErrorHelper.p_AEPSAD_Log(_response.StatusCode.ToString());
                }

                ViewBag.FontAwesome = DropDownListHelper.p_AEPSAD_FontAwesomeIconList();

                if (_list == null)
                    return View(_m);

                return View(_m);
            }

            catch (Exception ex)
            {
                ErrorHelper.p_AEPSAD_Log(ex);

                return RedirectToAction(ConfigHelper.URL_ERROR + "?" + ErrorHelper.ERROR_VARIABLE + "=" + ErrorHelper.ERROR_EXEC_KEY);
            }
        }

        [HttpPost]
        public ActionResult EditarMenuItems(Menu model, HttpPostedFileBase IconoFile)
        {
            model.GruposMenu = DropDownListHelper.p_AEPSAD_MenuGrupos(model.MenuGrupoId);           

            try
            {

                String _error = String.Empty;
                String _icono = String.Empty;

                bool _isFileUploaded = UploadImageHelper.p_AEPSAD_UploadImage(IconoFile, "IconoMenu_" + model.Id, ref _icono, ref _error);

                if (!_isFileUploaded)
                {
                    ModelState.AddModelError("IconoFile", _error);
                }

                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                MenuModel _m = new MenuModel
                {
                    Id = model.Id,
                    MenuGrupoId = model.MenuGrupoId,
                    Texto = model.Texto,
                    Enlace = model.Enlace,
                    Icono = _icono,
                    NuevaVentana = (model.NuevaVentana ? Convert.ToByte(1) : Convert.ToByte(0)),
                    Orden = model.Orden
                };


                HttpClient _client = WebApiHelper.p_APESAD_HttpClient(SessionHelper.p_AEPSAD_get_usuario().Token);


                var _json = JsonConvert.SerializeObject(_m);
                var _content = new StringContent(_json.ToString(), Encoding.UTF8, "application/json");

                HttpResponseMessage _response = _client.PutAsync(WebApiHelper.ENDPOINT_MENU_UPDATE, _content).Result;

                if (_response.IsSuccessStatusCode)
                {
                    ViewBag.JavaScriptFunction = string.Format("p_AEPSAD_save_ok('Los datos han sido actualizados');");
                }
                else
                {
                    ErrorHelper.p_AEPSAD_Log(_response.ReasonPhrase);
                    ViewBag.JavaScriptFunction = string.Format("p_AEPSAD_error('" + _response.ReasonPhrase + "');");
                }

                return View(model);
            }
            catch (Exception ex)
            {
                ErrorHelper.p_AEPSAD_Log(ex);
                ViewBag.JavaScriptFunction = string.Format("p_AEPSAD_error('" + ex.Message + "');");
                return View(model);
            }
        }

        [HttpGet]
        public async Task<ActionResult> EliminarMenuItems(String id)
        {

            try
            {                
                HttpClient _client = WebApiHelper.p_APESAD_HttpClient(SessionHelper.p_AEPSAD_get_usuario().Token);

                HttpResponseMessage _response = await _client.DeleteAsync(WebApiHelper.ENDPOINT_MENU_DELETE + id);

                if (_response.IsSuccessStatusCode)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.OK);
                }
                else
                {
                    ErrorHelper.p_AEPSAD_Log(_response.StatusCode.ToString());

                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Error en el WebApi");
                }
            }
            catch (Exception ex)
            {

                ErrorHelper.p_AEPSAD_Log(ex);

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ex.Message);
            }
        }


        #region Grupos Menu

        /// <summary>
        /// Listado sin filtro
        /// </summary>
        /// <returns></returns>
        public ActionResult GruposMenu()
        {
            try
            {
                List<vBack_GruposMenuList> _list = new List<vBack_GruposMenuList>();
                HttpResponseMessage _response = WebApiHelper.p_AEPSAD_Request(WebApiHelper.ENDPOINT_MENU_GRUPOS_GETALL);

                if (_response.IsSuccessStatusCode)
                {
                    var _json = _response.Content.ReadAsStringAsync().Result;

                    _list = JsonConvert.DeserializeObject<List<vBack_GruposMenuList>>(_json);
                }
                else
                {
                    ErrorHelper.p_AEPSAD_Log(_response.StatusCode.ToString());
                }

                if (_list == null)
                    return View(new List<vBack_GruposMenuList>());

                ViewBag.Opciones = DropDownListHelper.p_AEPSAD_Modulos();

                return View(_list);
            }

            catch (Exception ex)
            {
                ErrorHelper.p_AEPSAD_Log(ex);

Back/Views/Shared/_Layout.cshtml
@using Back.Helpers;

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Back | Intranet AEPSAD - @ViewBag.Title</title>

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">
    <link rel="stylesheet" href="~/Content/Site.css" />

    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>


    <script src="~/Content/JS/Modalloading.js"></script>
    <script src="~/Content/JS/WindowsJS.js"></script>

</head>
<body class="body-content">
    <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#"><img src="~/Imgs/Logo.png" title="AEPSAD Intranet" /></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    @Html.ActionLink("Inicio", "Index", "Main", new object { }, new { @class = "nav-link", onclick = "waitingDialog.show();" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Noticias", "Index", "Noticias", new object { }, new { @class = "nav-link", onclick = "waitingDialog.show();" })
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Menu
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        @Html.ActionLink("Grupos", "GruposMenu", "Menu", new object { }, new { @class = "dropdown-item", onclick = "waitingDialog.show();" })
                        @Html.ActionLink("Items menú", "MenuItems", "Menu", new object { }, new { @class = "dropdown-item", onclick = "waitingDialog.show();" })
                    </div>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                @Html.ActionLink("Salir", "LogOut", "Home", new object { }, new { @class = "btn btn-danger" })

            </form>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>

    <script>

    $(document).ready(function () {    
        waitingDialog.hide();
    });

    </script>

</body>
</html>